//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfexewcftest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyMathService")]
    public interface IMyMathService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMathService/Add", ReplyAction="http://tempuri.org/IMyMathService/AddResponse")]
        double Add(double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMathService/Add", ReplyAction="http://tempuri.org/IMyMathService/AddResponse")]
        System.Threading.Tasks.Task<double> AddAsync(double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMathService/Subtract", ReplyAction="http://tempuri.org/IMyMathService/SubtractResponse")]
        double Subtract(double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMathService/Subtract", ReplyAction="http://tempuri.org/IMyMathService/SubtractResponse")]
        System.Threading.Tasks.Task<double> SubtractAsync(double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMathService/Multiply", ReplyAction="http://tempuri.org/IMyMathService/MultiplyResponse")]
        double Multiply(double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMathService/Multiply", ReplyAction="http://tempuri.org/IMyMathService/MultiplyResponse")]
        System.Threading.Tasks.Task<double> MultiplyAsync(double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMathService/Divide", ReplyAction="http://tempuri.org/IMyMathService/DivideResponse")]
        double Divide(double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMathService/Divide", ReplyAction="http://tempuri.org/IMyMathService/DivideResponse")]
        System.Threading.Tasks.Task<double> DivideAsync(double dblNum1, double dblNum2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyMathServiceChannel : cfexewcftest.ServiceReference1.IMyMathService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyMathServiceClient : System.ServiceModel.ClientBase<cfexewcftest.ServiceReference1.IMyMathService>, cfexewcftest.ServiceReference1.IMyMathService {
        
        public MyMathServiceClient() {
        }
        
        public MyMathServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyMathServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMathServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMathServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Add(double dblNum1, double dblNum2) {
            return base.Channel.Add(dblNum1, dblNum2);
        }
        
        public System.Threading.Tasks.Task<double> AddAsync(double dblNum1, double dblNum2) {
            return base.Channel.AddAsync(dblNum1, dblNum2);
        }
        
        public double Subtract(double dblNum1, double dblNum2) {
            return base.Channel.Subtract(dblNum1, dblNum2);
        }
        
        public System.Threading.Tasks.Task<double> SubtractAsync(double dblNum1, double dblNum2) {
            return base.Channel.SubtractAsync(dblNum1, dblNum2);
        }
        
        public double Multiply(double dblNum1, double dblNum2) {
            return base.Channel.Multiply(dblNum1, dblNum2);
        }
        
        public System.Threading.Tasks.Task<double> MultiplyAsync(double dblNum1, double dblNum2) {
            return base.Channel.MultiplyAsync(dblNum1, dblNum2);
        }
        
        public double Divide(double dblNum1, double dblNum2) {
            return base.Channel.Divide(dblNum1, dblNum2);
        }
        
        public System.Threading.Tasks.Task<double> DivideAsync(double dblNum1, double dblNum2) {
            return base.Channel.DivideAsync(dblNum1, dblNum2);
        }
    }
}
